name: CI / CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t hello-devops:latest .

      - name: Run NGINX Container in Background
        run: docker run -d -p 8081:80 --name test-nginx hello-devops:latest

      - name: Wait for NGINX to start
        run: sleep 5

      - name: Run Tests from outside container
        run: |
          echo "✅ Début des tests..."
          if curl -s http://localhost:8081 | grep -q "Hello"; then
            echo "✅ Test de page d'accueil : OK"
          else
            echo "❌ Test de page d'accueil : ÉCHEC"
            exit 1
          fi
          echo "✅ Tous les tests sont passés avec succès !"

      - name: Stop and Remove Container
        run: docker stop test-nginx

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        
      - name: Pull Docker Image from Docker Hub
        run: docker pull nadajoobeur/hello-devops:v1.0

      - name: Tag Docker Image
        run: docker tag hello-devops:latest nadajoobeur/hello-devops:v1.0

      - name: Push Docker Image
        run: docker push nadajoobeur/hello-devops:v1.0

      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/deployment.yaml
